fix: check for node version

diff --git a/dev/Dockerfile b/dev/Dockerfile
--- a/dev/Dockerfile
+++ b/dev/Dockerfile
@@ -2,20 +2,24 @@ FROM base
 
 ARG NODE_VERSION=22
 
-ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 \
-    PHP_OPCACHE_FILE_OVERRIDE=0
-
 USER root
 
 RUN <<EOF
     set -e
-    NODE_PREFIX=""
 
     if [[ "$NODE_VERSION" == "24" ]]; then
-        NODE_PREFIX="-current"
+        apk add \
+            --no-cache \
+            --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
+            nodejs-current npm
+    else
+        apk add \
+            --no-cache \
+            --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
+            nodejs npm
     fi
 
-    apk add --no-cache npm bash nodejs${NODE_PREFIX}
+    apk add --no-cache npm bash
     install-php-extensions tideways blackfire xdebug
 
     cd /usr/local/etc/php/conf.d
@@ -25,12 +29,21 @@ RUN <<EOF
     mv docker-php-ext-blackfire.ini docker-php-ext-blackfire.disabled
 
     chown -R www-data:www-data /usr/local/etc/php/conf.d
+
+    INSTALLED_NODE_VERSION=$(node -e "console.log(process.versions.node.substr(0,2))")
+    if [[ "$INSTALLED_NODE_VERSION" != "$NODE_VERSION" ]]; then
+        echo "ERROR: Installed Node.js version ($INSTALLED_NODE_VERSION) does not match expected version ($NODE_VERSION)"
+        exit 1
+    fi
 EOF
 
 USER www-data
 
 COPY --link --from=ghcr.io/shopware/shopware-cli:bin /shopware-cli /usr/local/bin/shopware-cli
 COPY --link rootfs /
+
+ENV PHP_OPCACHE_VALIDATE_TIMESTAMPS=1 \
+    PHP_OPCACHE_FILE_OVERRIDE=0
 
 ENTRYPOINT [ "/entrypoint" ]
 CMD [ "/usr/bin/supervisord", "-c", "/etc/supervisord.conf" ]
